<<<<<<< HEAD
services:
  web:
    container_name: next-web
    build:
      context: .
      dockerfile: ./apps/web/Dockerfile
    ports:
      - "3000:3000"
    env_file:
      - ./apps/web/.env
    depends_on:
      api:
        condition: service_healthy
    restart: unless-stopped

  api:
    container_name: nest-api
    build:
      context: .
      dockerfile: ./apps/api/Dockerfile
    ports:
      - "3001:3001"
    env_file:
      - ./apps/api/.env
    healthcheck:
      test: [ "CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:3001/api" ]
      interval: 5s
      timeout: 3s
      retries: 5
      start_period: 10s
    restart: unless-stopped

  postgres:
    image: postgres:16
    container_name: job-matcher-postgres
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: job-matcher-pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    ports:
      - "5050:80"
    depends_on:
      - postgres

volumes:
  postgres_data:
=======
[?2004h[?1049h[22;0;0t[1;34r(B[m[4l[?7h[39;49m[?1h=[?1h=[?25l[39;49m(B[m[H[2J(B[0;7m  GNU nano 6.2                                                                                      New Buffer                                                                                               [1;204H(B[m[32;78H(B[0;7m[ Welcome to nano.  For basic help, type Ctrl+G. ](B[m[33d(B[0;7m^G(B[m Help[33;18H(B[0;7m^O(B[m Write Out     (B[0;7m^W(B[m Where Is[52G(B[0;7m^K(B[m Cut[33;69H(B[0;7m^T(B[m Execute[86G(B[0;7m^C(B[m Location[103G(B[0;7mM-U(B[m Undo[33;120H(B[0;7mM-A(B[m Set Mark     (B[0;7mM-](B[m To Bracket   (B[0;7mM-Q(B[m Previous     (B[0;7m^B(B[m Back[33;188H(B[0;7m^◂(B[m Prev Word[34d(B[0;7m^X(B[m Exit[34;18H(B[0;7m^R(B[m Read File     (B[0;7m^\(B[m Replace[52G(B[0;7m^U(B[m Paste[34;69H(B[0;7m^J(B[m Justify[86G(B[0;7m^/(B[m Go To Line    (B[0;7mM-E(B[m Redo[34;120H(B[0;7mM-6(B[m Copy[34;137H(B[0;7m^Q(B[m Where Was     (B[0;7mM-W(B[m Next[34;171H(B[0;7m^F(B[m Forward[188G(B[0;7m^▸(B[m Next Word[2d[?12l[?25h[?25l[32;76H(B[0;7m[ line  1/1 (100%), col  1/ 1 (100%), char  0/0 ( 0%) ](B[m[?12l[?25h[2d[?25l[32;131H[?12l[?25h[2d[?25l[32;131H[?12l[?25h[2d[?25l[32;131H[?12l[?25h[2d[?25l[32d[J[34d[?12l[?25h[34;1H[?1049l[23;0;0t[?1l>[?2004l
>>>>>>> 401f4c6 (setup postgres docker)
