export const SECTION_ALIAS_TO_CANONICAL: Record<string, string> = {
  summary: 'summary',
  profile: 'summary',
  'career goals': 'summary',
  'career goal': 'summary',
  'muc tieu': 'summary',
  'professional summary': 'summary',
  objective: 'summary',
  'career objective': 'summary',
  'tom tat': 'summary',
  'gioi thieu': 'summary',
  'muc tieu nghe nghiep': 'summary',
  'tóm tắt': 'summary',
  'giới thiệu': 'summary',
  'mục tiêu nghề nghiệp': 'summary',

  experience: 'experience',
  'work experience': 'experience',
  'employment history': 'experience',
  'career history': 'experience',
  'professional experience': 'experience',
  'kinh nghiem': 'experience',
  'kinh nghiem lam viec': 'experience',
  'qua trinh cong tac': 'experience',
  'kinh nghiệm': 'experience',
  'kinh nghiệm làm việc': 'experience',
  'quá trình công tác': 'experience',
  'internship experience': 'experience',
  'intern experience': 'experience',

  education: 'education',
  'education level': 'education',
  'education background': 'education',
  'academic level': 'education',
  'academic background': 'education',
  qualifications: 'education',
  'hoc van': 'education',
  'trinh do hoc van': 'education',
  'học vấn': 'education',
  'trình độ học vấn': 'education',

  skills: 'skills',
  skill: 'skills',
  'technical skills': 'skills',
  'core skills': 'skills',
  competencies: 'skills',
  'ky nang': 'skills',
  'ky nang chuyen mon': 'skills',
  'kỹ năng': 'skills',
  'kỹ năng chuyên môn': 'skills',
  'ki nang': 'skills', // FIX: common mis-diacritic variant (kĩ năng)
  'kĩ năng': 'skills',

  projects: 'projects',
  'project experience': 'projects',
  'selected projects': 'projects',
  activity: 'experience',
  activities: 'experience',
  'work activities': 'experience',
  'hoat dong': 'experience',
  'hoạt động': 'experience',
  'du an': 'projects',
  'dự án': 'projects',
  'du an ca nhan': 'projects',
  'dự án cá nhân': 'projects',

  certifications: 'certifications',
  certificates: 'certifications',
  licenses: 'certifications',
  'chung chi': 'certifications',
  'chứng chỉ': 'certifications',

  languages: 'languages',
  'language proficiency': 'languages',
  'ngoai ngu': 'languages',
  'ngon ngu': 'languages',
  'ngoại ngữ': 'languages',
  'ngôn ngữ': 'languages',

  contact: 'contact',
  'contact information': 'contact',
  'personal information': 'contact',
  'lien he': 'contact',
  'thong tin lien he': 'contact',
  'thong tin ca nhan': 'contact',
  'liên hệ': 'contact',
  'thông tin liên hệ': 'contact',
  'thông tin cá nhân': 'contact',

  awards: 'awards',
  achievements: 'awards',
  honors: 'awards',
  'thanh tich': 'awards',
  'giai thuong': 'awards',
  'thành tích': 'awards',
  'giải thưởng': 'awards',

  interests: 'interests',
  hobbies: 'interests',
  'so thich': 'interests',
  'sở thích': 'interests',
};
