api:
  container_name: nest-api
  build:
    context: .
    dockerfile: ./apps/api/Dockerfile
  ports:
    - "3001:3001"
  env_file:
    - ./apps/api/.env
  depends_on:
    - postgres
  restart: unless-stopped